---
version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysqlfordocker}
      MYSQL_DATABASE: ${DB_NAME:-atlasdb}
      MYSQL_USER: ${DB_USERNAME:-atlas}
      MYSQL_PASSWORD: ${DB_PASSWORD:-iamatlas}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: "exit 0"

  atlas:
    image: openmrs/atlas:production
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_NAME: ${DB_NAME:-atlasdb}
      DB_USERNAME: ${DB_USERNAME:-atlas}
      DB_PASSWORD: ${DB_PASSWORD:-iamatlas}
      TIME_ZONE: ${TIME_ZONE:-America/New_York}
      PING_DELETE_SECRET: ${PING_DELETE_SECRET:-secret}
      API_KEY: ${API_KEY:-1234567890abcdef}
      SITE_KEY: ${SITE_KEY:-localhost}
      ID_HOST: ${ID_HOST:-http://localhost}
      SITE_URL: ${SITE_URL:-http://localhost}
      GOOGLE_MAPS_JS_API_KEY: ${GOOGLE_MAPS_JS_API_KEY:-XXXXXXXXXXX_XXXXXX-XXXXXXXXXXX-XXXXXXXX}
    ports:
      - 8548:80
    volumes:
      - atlas-storage:/var/www/html/atlas/app/storage
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/markerSites/"]

  backup:
    image: openmrs/cron-backup
    depends_on:
      - db
    volumes:
      - mysql-data:/mysql_data
      - atlas-storage:/atlas-storage
      - ${BACKUP_DIR-./backups}:/backup
    environment:
      - DIRS=/mysql_data:atlas_mysql,/atlas-storage:atlas_storage
      - SCHEDULE=0 0 * * *
    restart: always
    healthcheck:
      test: "exit 0"

volumes:
  mysql-data:
  atlas-storage:
