#!/bin/bash -eu

# Deploy docker-compose application

ENVIRONMENT=$1
FORCE_DESTROY_VOLUMES=${2:-false}
FORCE_DESTROY_NETWORKS=${3:-true}

cd /root/docker/$ENVIRONMENT
docker-compose pull

[ -s ./deploy.env ] && source ./deploy.env
DESTROY_VOLUMES=${DESTROY_VOLUMES:-true}
DESTROY_NETWORKS=${DESTROY_NETWORKS:-true}

downcmd="down"
if [[ ! ("${FORCE_DESTROY_NETWORKS}" == "true" && "${DESTROY_NETWORKS}" == "true") ]]; then
  downcmd="rm -f -s"
fi

volumes=""
if [[ ! ("${FORCE_DESTROY_VOLUMES}" == "false" && "${DESTROY_VOLUMES}" == "false") ]]; then
  volumes="-v"
fi

docker-compose $downcmd $volumes

docker-compose up -d

containers=$(docker-compose ps -q)
n=0
until [ $n -ge 30 ]
do
  echo "Verifying if docker containers ${containers} are healthy"
  health_check=$(docker inspect --format='{{json .State.Health.Status}}' $containers | sort -u )
  echo "Status found: "${health_check}
  test "${health_check}" = '"healthy"' && exit 0
  echo "Waiting 15s"
  n=$[$n+1]
  sleep 15
done

echo "####################################################"
docker logs -f

exit 1
