#!/bin/bash -eu

ENVIRONMENT=$1
IMAGE=$2

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd /root/docker/$ENVIRONMENT
result_dc=$(docker-compose pull)

if echo "$result_dc" | fgrep "Status: Downloaded newer image for openmrs/${IMAGE}"; then
  echo "New image downloaded for ${IMAGE}"
  $DIR/deploy-compose $ENVIRONMENT
else
  echo "No newer images found"
  exit 0
fi
