#!/bin/bash -eu

ENVIRONMENTS=$(echo $1 | tr ',' ' ')
IMAGE=$2
FORCE_DESTROY_VOLUMES=${3:-false}
FORCE_RESTART=${4:-false}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Check if using old or new docker compose
if command -v docker-compose >/dev/null 2>&1; then
    DOCKER_COMPOSE=(docker-compose)
else
    DOCKER_COMPOSE=(docker compose)
fi

for ENVIRONMENT in $ENVIRONMENTS; do
  echo "Running environment $ENVIRONMENT"
  (
    cd /root/docker/$ENVIRONMENT
    result_dc=$("${DOCKER_COMPOSE[@]}" pull 2>&1)

    if echo "$result_dc" | fgrep "Status: Downloaded newer image for ${IMAGE}"; then
      echo "New image downloaded for ${IMAGE}"
      $DIR/deploy-compose $ENVIRONMENT $FORCE_DESTROY_VOLUMES $FORCE_RESTART
    else
      echo "No newer images found"
      exit 0
    fi
  ) > /root/docker/${ENVIRONMENT}/deploy.log 2>&1
done
