version: "3.7"

services:
  # Proxy
  proxy:
    image: openmrs/openmrs-reference-application-3-gateway:latest
    ports:
      - 8084:80
    healthcheck:
      test: exit 0 

  # Frontend
  frontend:
    image: openmrs/openmrs-reference-application-3-frontend:latest
    environment:
      SPA_PATH: /openmrs/spa
      API_URL: /openmrs
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost:8080/ui/index.html"]
      timeout: 5s

  # OpenMRS:
  openmrs:
    image: openmrs/openmrs-reference-application-3-backend:latest
    depends_on:
      - db
    environment:
      OMRS_CONFIG_MODULE_WEB_ADMIN: "false"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "false"
      OMRS_CONFIG_CREATE_TABLES: "true"
      OMRS_CONFIG_CONNECTION_SERVER: db
      OMRS_CONFIG_CONNECTION_DATABASE: ${OPENMRS_DB:-openmrs}
      OMRS_CONFIG_CONNECTION_USERNAME: ${OPENMRS_DB_USER:-openmrs}
      OMRS_CONFIG_CONNECTION_PASSWORD: ${OPENMRS_DB_PASSWORD:-Admin123}
    healthcheck:
      test: ["CMD", "curl", "-fsSL", "http://localhost:8080/openmrs"]
      timeout: 5s
    volumes:
      - openmrs-data:/openmrs/data

  # MariaDB
  db:
    image: mariadb:10.3
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: ${OPENMRS_DB:-openmrs}
      MYSQL_USER: ${OPENMRS_DB_USER:-openmrs}
      MYSQL_PASSWORD: ${OPENMRS_DB_PASSWORD:-Admin123}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin123}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  openmrs-data: ~
  db-data: ~
